Add special treatment of d-special in nvim from vimscript side (#68)
* Add special treatment of d-special in nvim from vimscript side

* Fix `virtcol2col()` usage

* Recognize test case as d-special

* Don't compile nvim from source; download its github release instead

Because different versions of nvim seems to need to be compiled
differently.

* Revert to python 3.11 as was used in the old CI pipeline

Because vim v8.2 somehow won't launch with python 3.9.

* Add d-special test case for nvim

* Fix not adding vim/nvim to PATH on cache hit

* Can't get vim v8.2 working, trying with patch 2876

See e.g. <https://groups.google.com/g/vim_dev/c/w6nF3mL-CaM>.

* Tweaking vim compilation flags

* Okay vim 8.2.2876 works, let's try reverting it back

This reverts commit a8f17e0f320943c87c2e1edf381d45faaed48db1.

* Debugging job `commit_change`

* Got it, the culprit is vim 8.2 patch 0000; we will stick with patch 2876

Could have tried bisecting for the earliest patch that works. However
we don't have that much time.

* Don't ignore jieba test cases expanded from j2 templates

* Ensure the generated rust tests are named properly

* Add empty placeholder test cases to prevent git-add issue

See <https://github.com/stefanzweifel/git-auto-commit-action/issues/227>
for details.

* Remove debugging lines

* Update tests

diff --git a/.github/actions/setup-vim/action.yml b/.github/actions/setup-vim/action.yml
--- a/.github/actions/setup-vim/action.yml
+++ b/.github/actions/setup-vim/action.yml
@@ -8,7 +8,7 @@ inputs:
     description: 'The vim/nvim version'
     required: true
   glue-lang:
-    description: 'The glue language (either "py39" or "lua51")'
+    description: 'The glue language (either "py311" or "lua51")'
     required: true
 runs:
   using: composite
@@ -16,12 +16,12 @@ runs:
     - name: Setup python
       uses: actions/setup-python@v6
       with:
-        python-version: '3.9'
-      if: ${{ inputs.glue-lang == 'py39' }}
+        python-version: '3.11'
+      if: ${{ inputs.glue-lang == 'py311' }}
     - name: Install pynvim
       shell: bash
       run: pip install pynvim
-      if: ${{ inputs.glue-lang == 'py39' && inputs.vim-distr == 'nvim' }}
+      if: ${{ inputs.glue-lang == 'py311' && inputs.vim-distr == 'nvim' }}
     - name: Setup lua
       uses: leafo/gh-actions-lua@master
       with:
@@ -39,7 +39,7 @@ runs:
       with:
         key: ${{ inputs.vim-distr }}-${{ inputs.vim-version }}-${{ inputs.glue-lang }}
         path: ~/vim
-    - name: Compile and install vim
+    - name: Compile and install vim to PATH
       if: ${{ inputs.vim-distr == 'vim' && steps.cache-vim.outputs.cache-hit != 'true' }}
       shell: bash
       run: |
@@ -47,20 +47,35 @@ runs:
         sudo apt-get install -y --no-install-recommends git make clang libtool-bin
         git clone https://github.com/vim/vim.git ~/vim
         cd ~/vim && git checkout ${{ inputs.vim-version }}
-        case ${{ inputs.glue-lang }} in
-          py39)
+        case "${{ inputs.glue-lang }}-${{ inputs.vim-version }}" in
+          py311-v9.*)
             LDFLAGS=-rdynamic ./configure \
               --with-features=huge \
               --enable-fail-if-missing \
               --enable-largefile \
               --enable-multibyte \
               --enable-python3interp \
-              --with-python3-command=python3.9 \
-              --with-python3-stable-abi=3.9 \
+              --with-python3-command=python3.11 \
+              --with-python3-stable-abi=3.11 \
               --enable-gui=no \
               --prefix="$HOME/vim/prefix"
             ;;
-          lua51)
+          py311-v8.*)
+            env \
+              vi_cv_path_python3_plibs="-L$(python3.11-config --configdir) -lpython3.11 -ldl -lm" \
+              vi_cv_var_python3_version=3.11 \
+              LDFLAGS=-rdynamic \
+              ./configure \
+              --with-features=huge \
+              --enable-fail-if-missing \
+              --enable-largefile \
+              --enable-multibyte \
+              --enable-python3interp \
+              --with-python3-command=python3.11 \
+              --with-python3-stable-abi=3.11 \
+              --prefix="$HOME/vim/prefix"
+            ;;
+          lua51-*)
             LDFLAGS=-rdynamic ./configure \
               --with-features=huge \
               --enable-fail-if-missing \
@@ -72,20 +87,41 @@ runs:
             ;;
         esac
         make && make install
-    - name: Compile and install nvim
+        echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
+    - name: Download and install nvim to PATH
       if: ${{ inputs.vim-distr == 'nvim' && steps.cache-vim.outputs.cache-hit != 'true' }}
       shell: bash
       run: |
         sudo apt-get update
-        sudo apt-get install -y --no-install-recommends git make clang libtool-bin cmake
-        git clone https://github.com/neovim/neovim ~/vim
-        cd ~/vim && git checkout ${{ inputs.vim-version }}
-        make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX="$HOME/vim/prefix"
-        make install
+        sudo apt-get install -y --no-install-recommends curl tar
+        case ${{ inputs.vim-version }} in
+          v0.10.2)
+            TARBALL_NAME=nvim-linux64
+            ;;
+          v0.11.5)
+            TARBALL_NAME=nvim-linux-x86_64
+            ;;
+          *)
+            echo "Invalid nvim vim-version: ${{ inputs.vim-version }}" >&2
+            false
+            ;;
+        esac
+        mkdir ~/vim
+        curl -fSL https://github.com/neovim/neovim/releases/download/${{ inputs.vim-version }}/${TARBALL_NAME}.tar.gz \
+          | tar xzf - --strip-components=1 -C ~/vim
+        echo "$HOME/vim/bin" >> $GITHUB_PATH
     - name: Add vim/nvim to PATH
+      if: ${{ steps.cache-vim.outputs.cache-hit == 'true' }}
       shell: bash
       run: |
-        echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
+        case ${{ inputs.vim-distr }} in
+          vim)
+            echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
+            ;;
+          nvim)
+            echo "$HOME/vim/bin" >> $GITHUB_PATH
+            ;;
+        esac
     - name: Print vim/nvim version
       shell: bash
       run: ${{ inputs.vim-distr }} --version
