Don't compile nvim from source; download its github release instead
Because different versions of nvim seems to need to be compiled
differently.

diff --git a/.github/actions/setup-vim/action.yml b/.github/actions/setup-vim/action.yml
--- a/.github/actions/setup-vim/action.yml
+++ b/.github/actions/setup-vim/action.yml
@@ -39,7 +39,7 @@ runs:
       with:
         key: ${{ inputs.vim-distr }}-${{ inputs.vim-version }}-${{ inputs.glue-lang }}
         path: ~/vim
-    - name: Compile and install vim
+    - name: Compile and install vim to PATH
       if: ${{ inputs.vim-distr == 'vim' && steps.cache-vim.outputs.cache-hit != 'true' }}
       shell: bash
       run: |
@@ -72,20 +72,29 @@ runs:
             ;;
         esac
         make && make install
-    - name: Compile and install nvim
+        echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
+    - name: Download and install nvim to PATH
       if: ${{ inputs.vim-distr == 'nvim' && steps.cache-vim.outputs.cache-hit != 'true' }}
       shell: bash
       run: |
         sudo apt-get update
-        sudo apt-get install -y --no-install-recommends git make clang libtool-bin cmake
-        git clone https://github.com/neovim/neovim ~/vim
-        cd ~/vim && git checkout ${{ inputs.vim-version }}
-        make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX="$HOME/vim/prefix"
-        make install
-    - name: Add vim/nvim to PATH
-      shell: bash
-      run: |
-        echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
+        sudo apt-get install -y --no-install-recommends curl tar
+        case ${{ inputs.vim-version }} in
+          v0.10.2)
+            TARBALL_NAME=nvim-linux64
+            ;;
+          v0.11.5)
+            TARBALL_NAME=nvim-linux-x86_64
+            ;;
+          *)
+            echo "Invalid nvim vim-version: ${{ inputs.vim-version }}" >&2
+            false
+            ;;
+        esac
+        mkdir ~/vim
+        curl -fSL https://github.com/neovim/neovim/releases/download/${{ inputs.vim-version }}/${TARBALL_NAME}.tar.gz \
+          | tar xzf - --strip-components=1 -C ~/vim
+        echo "$HOME/vim/bin" >> $GITHUB_PATH
     - name: Print vim/nvim version
       shell: bash
       run: ${{ inputs.vim-distr }} --version
